sudo: required

language: java

services:
  - docker

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

before_install:
  - docker pull landoop/kafka-lenses-dev:2.0

install:
  - docker run -d -e ADV_HOST=127.0.0.1 -e EULA="https://dl.lenses.stream/d/?id=2d3c06ae-5b98-47e4-bb47-233b01f89621" --rm -p 3030:3030 -p 9092:9092 -p 2181:2181 -p 8081:8081 -p 9581:9581 -p 9582:9582 -p 9584:9584 -p 9585:9585 landoop/kafka-lenses-dev:2.0

before_script:
  - sleep 45

script: ./gradlew wrapper --gradle-version 4.6 clean test --stacktrace