sudo: required

language: java

services:
  - docker

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

before_install:
- docker run -d -p 2181:2181 -p 3030:3030 -p 8081-8083:8081-8083 -p 9581-9585:9581-9585 -p 9092:9092 -e ADV_HOST=127.0.0.1 -e RUNNING_SAMPLEDATA=1 landoop/kafka-lenses-dev:2.0

install: /bin/true

script: ./gradlew wrapper --gradle-version 4.6 clean test